# travis

language: generic
sudo: false
dist: trusty

before_install:
  - bash --version
  - openssl version
  - ssh -V

script:
  - |
      bash --posix ./create-root-ca -l -d travis-ca <<EOF
      n
      travis-ca
      bogus.com
      US
      California
      San Francisco
      Bogus Inc.
      Operations
      Bogus Inc. Certificate Authority
      rootCA_password
      rootCA_password
      EOF
  - cd travis-ca/
  - |
      bash --posix ./bin/create-server -s travis-server.bogus.com -a www.travis-server.bogus.com << EOF
      rootCA_password
      California
      San Francisco
      Jurisdiction of travis-server.bogus-com
      n
      EOF
  - |
      bash --posix ./bin/create-client -c travis-client << EOF
      rootCA_password
      San Francisco
      private
      travis-client@bogus.com
      n

      EOF
  - |
      bash --posix ./bin/create-codesign -c travis-codesign << EOF
      rootCA_password
      San Francisco
      private
      travis-codesign@bogus.com
      n
      codesign_p12pass
      EOF
  - |
      bash --posix ./bin/revoke-cert -c certs/server/travis-server-bogus-com/travis-server-bogus-com.crt << EOF
      1
      y
      rootCA_password
      EOF
  - |
      bash --posix ./bin/revoke-cert -c certs/codesign/travis-codesign/travis-codesign.crt << EOF
      6
      y
      rootCA_password
      EOF
  - |
      bash --posix ./bin/create-signing-ca -d travis-signing << EOF
      rootCA_password
      n
      travis-signing
      bogus.com
      US
      California
      San Francisco
      Bogus Inc.
      Operations
      Bogus Inc. Certificate travis-signing
      signCA_password
      signCA_password
      EOF
  - bash --posix ./bin/show-status
  - bash --posix ./bin/gen-html
  - cd travis-signing/
  - |
      bash --posix ./bin/create-server -s travis-server.bogus.com -a www.travis-server.bogus.com << EOF
      signCA_password
      California
      San Francisco
      Jurisdiction of travis-server.bogus-com
      n
      EOF
  - |
      bash --posix ./bin/create-client -c travis-client << EOF
      signCA_password
      San Francisco
      private
      travis-client@bogus.com
      n

      EOF
  - |
      bash --posix ./bin/revoke-cert -c certs/server/travis-server-bogus-com/travis-server-bogus-com.crt << EOF
      1
      y
      signCA_password
      EOF
  - |
      bash --posix ./bin/revoke-cert -c certs/clients/travis-client/travis-client.crt << EOF
      5
      y
      signCA_password
      EOF
  - bash --posix ./bin/show-status
  - bash --posix ./bin/gen-html
